config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount PdfjsViewer::Rails::Engine => "/pdfjs", as: 'pdfjs'

  resources :transcriptions
  root 'transcriptions#index'
end

app/models/transcription.rb
class Transcription < ActiveRecord::Base
  mount_uploader :pdf, PdfUploader
  mount_uploader :mp3, Mp3Uploader

  validates :song_title,
            :soloist_first_name,
            :soloist_last_name,
            :pdf,
            :mp3,
            presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/transcriptions_controller.rb
class TranscriptionsController < ApplicationController
  before_action :transcription,
                only: [:new, :show, :edit]
  before_action :authenticate_user!,
                only: [:new, :create, :edit, :update, :destroy]

  def index
    @transcriptions = Transcription.order(:soloist_last_name)
  end

  def new
  end

  def create
    @transcription = Transcription.new(transcription_params)

    if @transcription.save
      flash[:success] = 'Transcription Succesfully Created'
      redirect_to transcriptions_path
    else
      flash.now[:error] = 'There was a problem creating your transcription'
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if transcription.update_attributes(transcription_params)
      flash[:success] = 'Transcription Successfully Updated'
      redirect_to transcriptions_path
    else
      flash.now[:error] = 'There was a problem updating your transcription'
      render :edit
    end
  end

  def destroy
    transcription.destroy
    flash[:success] = 'Transcription Successfully Deleted'
    redirect_to transcriptions_path
  end

  private

  def transcription_params
    params.require(:transcription)
          .permit(
            :song_title,
            :soloist_first_name,
            :soloist_last_name,
            :pdf,
            :mp3
          )
  end

  def transcription
    @transcription ||=
      params[:id] ? Transcription.find(params[:id]) : Transcription.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!! 5
%html{lang: 'en'}
  %head
    %meta{charset: 'utf-8'}
    %meta{name: 'viewport', content: 'width=device-width, initial-scale=1.0'}

    %title= content_for?(:title) ? yield(:title) : 'Scott Macpherson'

    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags

  %body
    = render partial: 'shared/top_bar'
    = render partial: 'shared/flash'
    = yield

app/views/shared/_flash.html.haml
- flashes = {success: 'success', error: 'alert'}
- flashes.each do |key, value|
  - if flash[key]
    .alert-box{class: value, data: { alert: '' }}
      = flash[key]
      = link_to '&times;'.html_safe, '#', id: 'close'

app/views/shared/_top_bar.html.haml
.top-bar
  .top-bar-left
    %ul.dropdown.menu
      %li.menu-text= link_to 'Scott Macpherson', root_path
  .top-bar-right
    %ul.dropdown.menu
      %li= link_to 'Code', '#'
      %li= link_to 'Music', '#'
      %li= link_to 'Transcriptions', transcriptions_path
      %li= link_to 'Sign In', new_user_session_path

app/views/transcriptions/_error_messages.html.haml
- if @transcription.errors.any?
  .row.error_dialogue
    .large-12.columns
    The form contains #{pluralize(@transcription.errors.count, 'error')}:
    %ul
      - @transcription.errors.full_messages. each do |msg|
        %li= msg

app/views/transcriptions/_form.html.haml
= form_for @transcription, {class: 'medium-4 medium-offset-4 columns'} do |f|
  .row
    .large-12.column
      = f.label :song_title
      = f.text_field :song_title
    .large-12.column
      = f.label :soloist_first_name
      = f.text_field :soloist_first_name
    .large-12.column
      = f.label :soloist_last_name
      = f.text_field :soloist_last_name
    .large-12.column
      = f.label :pdf
      = f.file_field :pdf
    .large-12.column
      = f.label :mp3
      = f.file_field :mp3
    .large-12.column.transcription_submit
      = f.submit submit_button_name, {class: 'button'}

app/views/transcriptions/edit.html.haml
.row
  .large-12.columns.large-centered.transcription_header
    %h1 Edit Transcription

.row
  .large-12.columns.large-centered
    = render partial: 'error_messages'
.row
  .large-4.columns.large-centered
    = render partial: 'form', locals: { submit_button_name: 'Update Transcription' }

app/views/transcriptions/index.html.haml
.row
  .large-12.columns.transcription_header
    %h1.page_header Transcriptions

.row.new_button_div
  = link_to 'New Transcription', new_transcription_path, class: 'button'

.row
  .large-6.columns.large-centered
    %table.hover
      %thead
        %tr
          %th{width: '0.5rem'} Song
          %th{width: '0.5rem'} Artist
      %tbody
        - @transcriptions.each do |trans|
          %tr
            %td
              %em= link_to trans.song_title, trans
            %td
              = "#{trans.soloist_first_name} #{trans.soloist_last_name}"

app/views/transcriptions/new.html.haml
.row
  .large-12.columns.large-centered.transcription_header
    %h1 New Transcription

.row
  .large-12.columns.large-centered
    = render partial: 'error_messages'

.row
  .large-4.columns.large-centered
    = render partial: 'form', locals: { submit_button_name: 'Create Transcription' }

app/views/transcriptions/show.html.haml
.row
  #transcription_links.large-4.columns.large-centered
    .hollow.button= link_to('View Full Screen',
      pdfjs.full_path(file: image_path(@transcription.pdf)),
      target: '_blank')
    .hollow.button= link_to('Edit',
      edit_transcription_path(@transcription))
    .hollow.button= link_to('Delete',
      @transcription,
      method: :delete,
      data: { confirm: 'If you must...' })

.row
  #audio_player.large-12.columns
    = audio_tag @transcription.mp3,
      controls: true,
      preload: 'auto'


.row
  .large-12.columns#min_pdf_viewer
    %iframe{ src: pdfjs.minimal_path(file: image_path(@transcription.pdf)),
      height: '700px',
      width: '900px' }

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>